apiVersion: v1
kind: Service
metadata:
  name: book-store
  labels:
    app: book-store
    tier: service
spec:
 # use nodeport here to be able to access a port on each node
  type: NodePort
  ports:
  - port: 8089
  selector:
    app: book-store