apiVersion: v1
kind: Pod
metadata:
  name: book-store
  labels:
    language: go
    env: test
spec:
  containers:
  - name: book-store
    image: book-store:1.0.1-alpine
    ports:
    - containerPort: 8089
      protocol: TCP
